[project]
name = "browse"
version = "1.0.0"
description = "arXiv public browse and download app."
authors = []
requires-python = "~=3.11.0"
readme = "README.md"
dependencies = [
    "MarkupSafe",
    "pydantic==2.*",
    "python-dateutil",
    "arxiv-base",
    "flask>=3.0.2,<4",
    "gunicorn>=23.0.0,<24",
]

[dependency-groups]
dev = [
    "beautifulsoup4",
    "coverage",
    "hypothesis",
    "mypy",
    "pycodestyle",
    "pydocstyle",
    "pylint",
    "pytest",
    "pytest-cov",
    "pytest-easyread",
    "pytest-html",
    "pytest-mock",
    "types-requests>=2.31.0.20240125,<3",
    "requests-mock>=1.12.1,<2",
    "ruff>=0.11.8,<0.12",
]

[tool.uv]
exclude-newer = "1 week"
exclude-newer-package = { arxiv-base = "1 minute" }

[tool.uv.sources]
arxiv-base = { git = "https://github.com/arXiv/arxiv-base.git", branch = "master" }


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore:As the c extension couldn't be imported, `google-crc32c` is using a pure python implementation that is significantly slower. If possible, please configure a c build environment and compile the extension:RuntimeWarning",
]
